export const testimonials = [
  {
    text: "I recently stayed at this hotel premises with my colleagues for a day, and it was an amazing experience. Nestled in the hills, the hotel offered breathtaking views of the surrounding landscape, making it a perfect retreat from the city's hustle. The rooms were clean and well-maintained, providing a comfortable stay. The staff was friendly and attentive, ensuring a seamless experience. The food was delicious, with a variety of options to choose from. The serene ambiance and refreshing climate made our short stay truly memorable. I would highly recommend this hotel to anyone looking for a peaceful getaway in the hills.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Romantic, Quiet, Child-friendly",
    author: "Rishav K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "I had an excellent stay at this hotel! The rooms were spotless, spacious, and comfortable, with all the amenities I needed. The staff was incredibly friendly and attentive, always ready to help with a smile. The location was perfect, close to major attractions and convenient for exploring the city. The breakfast was delicious with a variety of options to choose from. Overall, a wonderful experience, and I would highly recommend this hotel to anyone looking for a relaxing and pleasant stay.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Child-friendly, Great value, High-tech",
    author: "Ajay S.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "This hotel is a fantastic choice for a holiday in a small town. Unlike Shimla or Manali, which have become commercialized, this place near Barog offers a much calmer and more serene experience. The hotel rooms are spacious, clean, and equipped with all the necessary facilities. The room service was excellent, and the food quality and taste were amazing. The hotel also features a rooftop seating area and a small swimming pool, adding to the overall experience. The view from the room balcony is stunning, making it perfect for a peaceful and relaxing getaway. If you visit on a new moon day, the location is ideal for stargazing.\n\nNearby activities: The hotel is conveniently located near several attractions. Kumarhatti market is just 3 km away, and after a 5 km drive, you can reach the starting point of a scenic trail that leads to the beautiful Barog railway station, offering lovely views and photo opportunities. Solan market, which is great for shopping, is about 15 km away. Additionally, if youre heading towards Chandigarh, a left turn approximately 15 km away will take you to the historic Dagshai cantonment, where you can explore the interesting Dagshai Jail Museum.\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Romantic, Quiet, Child-friendly, Great value",
    author: "Mohit K.",
    date: "November 2024",
    rating: 5,
  },
  {
    text: "Our stay in the hotel was unforgettable. We were a group of 12 families and it was super fantastic . The hotels elegant design with top notch amenities made for a spectacular stay in the hotel.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Shefali K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "I went with my family to Barog for a quiet getaway and it WAS worth it. Our stay in this beautiful hill station nestled in the gorgeous Shiwalik mountains was made even better at Le Halcyon. The hotel is conveniently approachable and has the most stunning view, its cleanliness is commendable and the rooms are extremely charming and has luxurious amenities. The staff is humble, helpful, understanding and so hospitable. The food tastes heavenly, especially in the fresh air of the hills. A must stay when you are in Himachal, the staff will make sure your experience is elevated a 1000 folds. Thank you Mahendra Ji for all the help and happy stay.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Apoorva C.",
    date: "November 2024",
    rating: 5,
  },
  {
    text: "Hotel situated at a very great location.Peaceful Place with great ambience.Nice Clean room with modern ammenities.Food is tasty and hygenic.\nRoom top area good for kids.\nResturant is equipped with good furniture and clean crockery.\nHotel staff is polite and coopertive.\nOverall wonderful stay at Hotel.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Quiet, High-tech",
    author: "Gaurav K.",
    date: "November 2024",
    rating: 5,
  },
  {
    text: "Amazing experience.. Good food and layout !! Courteous Staff .. Rooms were clean and tidy .\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Shweta S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Superb experience. The manager Mr Suresh Sharma and Mr Mahesh Thakur were very generous and generous.its a nice place to spend a weekend.the food was also excellent.\nRooms: 4/5 | Service: 5/5 | Location: 4/5\n\nHotel highlights\nLuxury",
    author: "Govind S.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Fantastic Hospitality ,Nice food , luxurious rooms,Mr. Sharma General Manager very polite. Best hotel in barobar hills kasauli\n\nHimachal.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Prachi K.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Best property and location, neat and clean room, fine dine restaurant.\n\nVery supportive and helpful senior management and staff.\n\nSpecial thanks to Mr. Hem Chand Rajput (MD), Mr. Suresh Sharma (GM), Mr. Mahendra Singh and Mr. Mahesh Thakur for being so courteous make my experience memorable.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Quiet, Child-friendly, Great value, High-tech",
    author: "Anurag S.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Excellent is everything.\nService, front desk staff are very polit.\nGood food. Good location\n\nRooms: Luxurious\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "New B.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Good location an view point. Good accommodation and food was good with good staff and service\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Vik",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Best hotel in kasauli Solan h\n\nBest room ,best service & best hospitality by Mr Sharma GM\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Naresh J.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "It was a great experience to stay at Le Halcyon. The service was was very nice and quick. The food was amazing and made the trip great .\n\nFood and drinks: The non veg was well tendered and the snacks were great.\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Ramesh N.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Amazing service and very cooperative staff . Well maintained room . Praveen Thakur and Mahesh Thakur we meet these 2 peoples who are welcoming and very nice .\n\nRooms: Rooms are spacious and very well organised\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat value",
    author: "Monika B.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Loved the place, an amazing view, place and worth every second of it.\nI would definitely recommend going here and will be coming here myself \n\nRooms: Comfortable bed, amazing service , beautiful walls and paintings\n\nSafety: Safe environment and no sharp or unkempt things and damage items\n\nNoteworthy details: Amazing aesthetic of the halls and rooms\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Child-friendly, Great value",
    author: "Sanah N.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Best hotel in barog kasauli ambiance was great location wise osm dileseouse food root top was amazing I recommend al my faimly and frenzied\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Child-friendly",
    author: "Jaspreet S.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Nice location. Good food. Nice rooms. Courtesy Staff at front desk.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Ravi C.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Courtesy Staff at front desk.Mr. Suresh & Mahender are very sporting. Food is excellent. MR. MAHESH & NAND LAL IN SERVICE IS IS POLITE. GOOD FOOD .\n\nAND EXCELLENT LOCATION .\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nChild-friendly",
    author: "Pardeep V.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Beautiful Hotel in kasauli Narog hills .\nLuxurious rooms good food .\nExcellent service. Perfect staff.\n\nRooms: Recommended to all family & friends\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Vikash G.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Best hotel in kaduali barog Solan. Really rnjoyed with our friends.best food service.Excellent location\n\nRooms: Top class stay\n\nFood and drinks: Top class food\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Vinit N.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Fantastic Hotel in Kasauli barog Solan Himachal Pradesh.\nGood food .nice location.\nLuxurious rooms . courtesy Staff.\n\nRooms: Luxurious\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Amit G.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Best For stay... Food was Awsome, Staff is polit\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Nikhil S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Fantastic trip. Luxurious rooms\n\n. Good food. Excellent service\n\nCourtesy Staff.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Rajiv B.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "The staff at this hotel were incredibly welcoming and helpful throughout our stay. The rooms were immaculate and very comfortable.\n\nRooms: Very nice and spacious rooms nice ambience nice wash rooms and the big thing is that the view from rooms.\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Beena B.",
    date: "November 2024",
    rating: 5,
  },
  {
    text: "I had a great stay in this hotel the room ware neet and clean\n\nIn the room eminities was full facility\n\nNice viwe in the room\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Sewak S.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Excellent performance by the management of hotel le halcyon. Everything is Excellent like food service and all .\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Swaran W.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Beautiful location\nGood amenities and food\nVery helpful/cordial staff\n\nWorth a stay\nHotel highlights\nQuiet, Child-friendly, Great value",
    author: "Ritesh S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "We enjoyed very much our staff trips.\n\nExcellent service provide by the halcyon staff. Good location.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Raj K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Very good experience and it was really wonderful stay.\nLove to visit this place again in future.\n\nFood and drinks: Excellent Food and quality of services up to the mark.\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Great value",
    author: "Ravi K.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Food is excellent. Nice location.Good service. Really good staff at front fest.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Romantic, Child-friendly",
    author: "Narender S.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Best hotel in kasauli barog hills solan hp\n\nExcellant service.\n\neverything was good.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Hardeep S.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Hotel Le halcyon is excellent for stay in kasauli barog hills Solan H.P.Good food . Good Service. Good location. Good location.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "M/S S.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Good location, wonderful views and nice hospitality! Enjoyed the stay with the family. Recommended\n\nRooms: Nice.\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Romantic, Child-friendly, Great value, High-tech",
    author: "Prreeti K.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Amazing hospitality. The location, rooms and the food everything was just perfect. If you are visiting barog, Solan,this is a must stay\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Bhawna K.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Fabulous experience\n\nFood was very delicious and tasty\n\nLocation and view awesome\n\nI really enjoyed\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Rajan G.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "The best option to stay in the area around Solan, Kasauli and Dagshai. The rooms are spacious and comfy, and the staff go out of their way to take care of everyone. It was our base for a couple of weeks recently, while we explored nearby areas. If you are visiting with family, then this is an excellent option - kids have a safe place to play and elders do not have to walk a lot to access rooms and the beautiful terrace! And yes, the food is amazing, especially the local cuisine that they serve :)\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Romantic, Quiet, Child-friendly, Great value",
    author: "Ketika K.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Nice Staff . Good food ,good location ,Beautiful hotel Kasauli Solan H.P.\n\n\nFood and drinks: Excellent .\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Bhagwan D.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Beautiful hotel nice location Ill recommend all my family and friends\n\nSpecially good was imaging\n\nTerrace view was excellent .\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Kanika J.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Our experience at Hotel Le Halcyon in Barog, Kasauli, Himachal Pradesh was nothing short of wonderful. The staff went above and beyond to make us feel welcome from the moment we arrived, their warmth and hospitality setting the tone for our stay.\n\nThe room surpassed our expectations in terms of comfort, offering a cozy and inviting retreat after a day of exploring the area. With its valley view, witnessing the sunset was truly heartwarming and added an extra layer of magic to our experience.\n\nOverall, Hotel Le Halcyon is a fantastic choice for those seeking a welcoming atmosphere and comfortable accommodations in the heart of Himachal Pradesh. We highly recommend it to anyone looking to make unforgettable memories amidst the serene beauty of Kasauli\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Atul P.",
    date: "June 2024",
    rating: 5,
  },
  {
    text: "Our stay at the hotel Le Halcyon was magnificent! The room was neat and clean with a beautiful view of the mountains. It was also equipped with every ingredient to make tea or coffee (water, electric kettle, dry milk packets, sugar, tea bags and coffee packets). The hotels food was delicious and the decoration and lights made us feel at home. We didnt have any issues with low network during our stay. Additionally, the hotel has WiFi available. The staff was kind and professional and to our convenience, they provided us a taxi to reach our destination safely. Overall, we fondly recommend this hotel to enjoy your stay, whether it is for some hours or a few days.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Quiet, Child-friendly, Great value, High-tech",
    author: "Yogesh S.",
    date: "May 2024",
    rating: 5,
  },
  {
    text: "This was my second visit. This time I came with my 4 friends. It was an awesome experience altogether. Best rooms, great view from private balcony and great hospitality. Rooms are really as shown on website. Washroom was awesome. Food is delicious. Will definitely recommend to everyone.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Child-friendly, Great value, High-tech",
    author: "Vinod S.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Lajwab hotel in kasauli barog hills\nGood food, good location. Good staff.\n\nRooms: Luxurious\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Gopal G.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Super hotel super breakfast super all service mahesh sir is good prson\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Darsh B.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Amazing experience and the staff is mind blowing praveen thakur mahesh thakur they are amazing person there skills is amazing in hospitality\n\nFood and drinks: Amazing food services\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Reshu D.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "The perfect place from which to explore Solan\nVery comfortable near and clean room. Plenty of electric sockets to charge my devices and work with my laptop. Great TV and really excellent hot shower, so easy to use. Friendly staff and fantastic breakfasts. Best part is its location and view from balconies.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Priti D.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "We organiz a corporate meeting in the hotel le halcyon. Staff,food ,location really was good .\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Sanyam K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "The location is very nice and good arrangement for parking. The customer service is Gud and rooms are spacious and clean. A must visit for Barog travellers. The facilities are optimum and I suggest that one should definitely visit this place. Thanks to team for a hospitable stay !!\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Kawalpreet S.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Excellent Service.\nPaisa vasul.\nGood food,nice location,and excellent service at front desk.\n\nRooms: Luxurious\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, High-tech",
    author: "Dharam S.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "We checked in on June 16, 2024. Our stay at Le Halcyon was fantastic. The staff provided excellent hospitality, making us feel very welcome. The property is beautiful and well-kept. Everything was spotlessly clean, from our room to the common areas. Highly recommend for a great stay.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Manish S.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "One of the best properties ever visited. Neither too far from the town but still has an offbeat location with a lot of peace and breathtaking views. We found out the rooms to be spacious and cozy having beautiful views from the balcony. Additionally the staff was also very cooperative and planned out a excellent Christmas event. Thank you team for a comfortable stay.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Great value, High-tech",
    author: "Mansimran K.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Very good Hotel, we enjoyed the stay here. Ambience was very good, rooms very clean and hygienic. Staff was nice and very supportive and understanding. Highly recommended.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Shalabh V.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "Pleasant stay .good location.Good food.\nGood rooms. Recmonded to all.\n\nRooms: Good everything.\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great value, High-tech",
    author: "Anand D.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "The best place to visit. They welcome the guest very nicely. The employees in the hotel were also very polite . They have kids section which was too gud. At last we had a wonderful experience with them\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Manmeet K.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "The property has a great ambiance with clean and cozy rooms. The staff is polite, helpful and well-mannered. The food is delicious and the property has good hygiene and safety standards. The property has a beautiful garden and a play area for all ages. a great place for couples and families to stay. Overall, a pleasant and comfortable stay.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sachin G.",
    date: "April 2024",
    rating: 5,
  },
  {
    text: "Amazing Hotel In Kasauli\n\nHotel Le Halcyon in Barog, Solan, is an amazing property with stunning views and exceptional amenities. Our family vacation here was truly memorable.\n\nThe rooms are spacious and well-appointed, with air conditioning and private balconies that offer breathtaking valley views. Each room is meticulously clean and well-maintained, providing a comfortable and luxurious stay.\n\nThe hospitality at Hotel Le Halcyon is outstanding. From the moment we arrived, we were warmly welcomed with a traditional Tika and complimentary refreshments. The staff are courteous, attentive, and go above and beyond to ensure guests have a pleasant experience.\n\nThe hotels location is ideal for exploring the surrounding area. It is close to notable attractions such as the historic Barog Tunnel, Mohan Heritage Park, and the serene Riva Waterfall. The picturesque setting adds to the charm of the stay.\n\nFood & Drinks: The food at Hotel Le Halcyon is up to the mark. The wide range of delicious dishes caters to various tastes, whether youre enjoying a hearty breakfast, a leisurely lunch, or a sumptuous dinner. The quality and taste of the food are consistently excellent.\n\nHotel Highlights:\n\nLuxury: The hotel offers a luxurious experience with top-notch amenities.\nGreat View: The valley views from the rooms and balconies are simply breathtaking.\nQuiet: The serene and quiet environment ensures a peaceful stay.\nKid-Friendly: The hotel is very accommodating to families and ensures a safe and enjoyable experience for children.\nGreat Value: The combination of luxury, service, and affordability makes this hotel an excellent choice for travelers.\nIn summary, Hotel Le Halcyon provides a perfect blend of luxury, comfort, and value. It is highly recommended for anyone seeking a memorable and comfortable stay in the Kasauli, Solan area.\n\nRooms: Luxurious rooms\n\nSafety: Safety locks and all things are available\n\nFood and drinks: Tasty food\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Great value, High-tech",
    author: "Jagjeet S.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Excellent are everything.\nGood location. Good food.\nNice location.\n\nRooms: Luxurious\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Sonu G.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Lovely staff! Polite and kind. Special thanks to Mr Mahesh. Awesome location. A must visit\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Mayank U.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Recently stayed at this beautiful property just 1.5 hours from Chandigarh. And I was amazed by its beauty. Every room in the property has a Balcony attached to it with a beautiful view of the mountains. The room are super luxurious with all the amenities. You will love the peaceful Vibes of the place. The staff is generous and helpful. They even have a restaurant which serves some really delicious food. You can plan for a bonfire night at the rooftop. Or you can go enjoy watching sunset along with high tea. The property is well connected to the main highway and Shimla is just 55 kms from the property.\nIf you want a relaxing stay away from the hustle bustle then this place is perfect for you.\nRooms: 5/5 | Service: 3/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Quiet, Great value",
    author: "Devang S.",
    date: "June 2024",
    rating: 5,
  },
  {
    text: "Absolute awesome. Had a great time with family. Superb hotel and most importantly view from the balcony was just mind blowing. Excellent staff. Highly recommend.  would love to visit again.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Vimal S.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Came across this place from a friend and then zeroed in on this hotel based on own research and , WoW , i was happy to be there the moment I checked in . The owner seems to have done lot of mental exercise keeping in mind the comfort of the guests while constructing and planning this hotel :\nLovely views\nConvenient location\nCourteous staff\nParking facility\nRoof top restaurant\nActivities for kids\nGreat tasty food\nGood power backup\nLIFT : that too in a hotel in the hills, full marks for that, elderly people will love it\n\nModern bathrooms with all amenities\nMore than i had expected\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Child-friendly",
    author: "Av S.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "We booked this hotel wit our corporate group.We really enjoyed very much.\n\nNice food nice rooms and beautiful location. Recommended to all.\n\nPaisa vasul.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Anil S.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "We went there with friends, our stay was superb here. This is a newly built hotel. Here are some of my observations:\nWhat was good:-\n- Newly built rooms\n- Spacious rooms, neat and clean\n- Rooftop for bonfires and parties\n- good views, with big balconies\n- Staff is well behaved\n- Food was good too in restaurant\n- Amenities- Electric kettle, Hair drier, dental kit, hot water available all the time, centrally AC. (4 star property)\n\nWhat can be Improved:\n- Parking available for 3-4 cars only\n\nOverall it was a quite good experience and value for money. I would surely love to visit again.\n\nRooms: Rooms are very good, neat and clean, with balconies with some good views.\n\nRooms: 5/5 | Service: 3/5 | Location: 4/5\n\nHotel highlights\nRomantic, Great value",
    author: "Ashwani K.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Excellent is everything.\n\nGood rooms ,good food,good services\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Vishu B.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Hotel Le Halcyon in Barog, Kasauli, in the Solan district, truly provides an exceptional experience that combines luxury and value.\n\nThe rooms are spacious and well-equipped, offering all modern amenities to ensure a comfortable stay. Each room is meticulously maintained, reflecting the high standards of cleanliness and service.\n\nThe hotels location is ideal for exploring nearby attractions. The historic Barog Tunnel, the fascinating Mohan Heritage Park, and the serene Riva Waterfall are all within easy reach. These sites provide a variety of activities and experiences for travelers interested in history, culture, and nature.\n\nThe check-in process is smooth and welcoming, with guests greeted with a traditional Tika and complimentary refreshments. This thoughtful gesture sets the tone for a warm and hospitable stay.\n\nThe food at Hotel Le Halcyon is delicious, offering a wide range of dishes that cater to various tastes. Whether you are enjoying a hearty breakfast, a leisurely lunch, or a sumptuous dinner, the quality and taste of the food are consistently excellent.\n\nThe staff at Hotel Le Halcyon are courteous and attentive, providing exceptional hospitality that makes guests feel valued and cared for. Their professionalism and friendliness contribute significantly to the overall positive experience at the hotel.\n\nIn summary, Hotel Le Halcyon offers an unbeatable combination of affordability, quality, and convenience. It is highly recommended for anyone looking for a memorable and comfortable stay in the Solan area.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Pallavi K.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Beautiful Hotel Barog hills kasauli\n\nLuxurious rooms ,Nice food. Nice Location.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Milind P.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Its a good accomodation in barog kasauli sach a comfortable stay in barog\n\nNice location.........\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Child-friendly",
    author: "Mansi P.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Excellent service.Good location.\n\nGood food\n\nRecommended to all\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Naksh K.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "The stay was pleasant and the services are beyond expectations \n\nThanks a lot.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Great value",
    author: "Radip N.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Excellent experience in hotel le halcyon hotel kasauli barog hills .\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Pankaj G.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Dear La Halcyon Hotelier,\n\nI am writing to express my deepest appreciation for the impeccable hospitality during my stay at your hotel near Solan. My family and I have just returned home after a three-day vacation that was rejuvenating, refreshing and an unforgettable experience.\n\nThe mesmerizing mountain views that surrounded the hotel, which is impossible to view in the city, were an absolute treat for our eyes. The scenic beauty that the hotel provided was breathtaking, and we surely would love to come back to relive those moments.\n\nWe were impressed with the high standard of cleanliness, and all the rooms were replete with the latest facilities and amenities that made our stay much more comfortable and enjoyable. Your dedication to maintaining cleanliness and hygiene was remarkable, and we commend you on achieving this level of excellence.\n\nThe inclusive package of breakfast and dinner provided with the booking was an added bonus. The food was delicious, and it gave us a taste of local cuisine. Your skilled chefs efforts were visible in every dish, and we enjoyed every meal we had while staying at the hotel.\n\nWe would like to thank you for providing us with such a wonderful vacation experience. The hospitality was exceptional, and every staff members cordial and warm attitude left a lasting impression on us. We have made many beautiful memories, and we hope to visit your hotel again soon.\n\nThank you again for making our vacation an unforgettable one.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Shailesh S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Lajawab hotel really\nEnjoy very much\nGood food\nGood rooms\nGood service\nGood staff\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat value",
    author: "Ajmer P.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "We had a please t stay with family at the hotel. The view from the room was amazing and the food and service is also good. Terrace has a trampoline and litte water pool for kids.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Quiet, Child-friendly",
    author: "Abhishek K.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Had kitty lunch here. We really had a blast. Food was tasty, well balanced in spices and service was cherry on the top. Very economical. View was awesome. Beautiful scenery around. Overall 5star\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Quiet, Child-friendly, Great value, High-tech",
    author: "Anurag D.",
    date: "April 2024",
    rating: 5,
  },
  {
    text: "Excellent location. Good rooms .good food .\n\nReally five star.Most budgeted hotel Solan , Kasauli.Barog hills.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, High-tech",
    author: "Chandershekhar G.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "Good location good staff specially food was osm\n\nHighly recommended........\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, High-tech",
    author: "Arun T.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Everything was perfect .. the view the fog the ambience and the best part the silence.. no traffic no unwanted noises nothing... completely enjoyed it.. hope to come here soon\n\nRooms: Very very neat and clean.\n\nSafety: Perfectly safe\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Child-friendly, High-tech",
    author: "Robin S.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "Awesome.. Awesome.. Awesome!!! I stayed in this hotel with my family for 3 days. And had a wonderful experience here. Thanks to this fabulous place. The staff is very polite, Manager Mr. Sharma is a very nice person. Service of staff is amazing, food they serve is delicious with a good variety. Location is just heavenly. Serene views, surrounded by nature, a calm and soothing. A soul pleasing place. The overall experience is more then wonderful. Highly recommend for family trips and for trip with friends.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Child-friendly, Great value",
    author: "Sonal A.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "It was a pleasant stay with good food and nice clean rooms.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Parag K.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Excellent stay with my friends and relatives. Awesome view. Good rooms good food.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Ravi N.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "Rooms were very beautiful, View was great . The restaurants food was very good. Service was nice but a little late . And the small pool water was very cold and has a few bugs which needs to be fixed .\n\nRooms: Very spacious and clean rooms, however washroom needs more cleanliness..\n\nFood and drinks: Resturant food quality is good but they take huge time to serve.\n\nRooms: 5/5 | Service: 4/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Quiet, Child-friendly, Great value",
    author: "Amrit B.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Great experience!!Good food!\n\nCourteous staff\nRooms: 4/5 | Service: 5/5 | Location: 5/5",
    author: "Swati V.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Excellent service.And everyone enjoyed\nGood location.Good staff of front desk\n\nNearby activities: Recommended to all\n\nNoteworthy details: Good\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great value, High-tech",
    author: "Rajat H.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Nice staff .good food.good rooms.good location. Recmoaded to all\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great value, High-tech",
    author: "Retu E.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Great experience nice room very neat and clean....and their food specially butter chicken we just love it but only problem is they give good quantity of food and much food will then left and waste so order accordingly that .... otherwise location from room is awesome and their staff is very cooperative and they give as return gift also we are very like this gesture thanks you so much for make our anniversary much more special sure to visit again soon .....\n\nRooms: Neat and clean\n\nFood and drinks: Food is awesome\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Great value",
    author: "Aarushi A.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Lovely Hotel. Nice location.courtesy staff.\n\nRooms: Luxurious\n\nSafety: Full safty\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Jeevan S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Everything is excellent . No doubt. Mr . Sharma is managing very carefully.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Gulpreet B.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "We checked in 12 Jun 24. It was a very comfortable stay in well appointed and clean rooms. Mr Vijay Sharma was very helpful and looked after us very graciously. Thank you for a stay and I would recommend Hotel Halcyon for a great stay.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Anand P.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Great hotel in barog kasouli\n\nReally enjoyed.....\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Rajeev S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Hotel Le Halcyon is one of the best hotels I have ever seen in the hills. Great location and beautifully surrounded by pine trees. The view from the hotel, specially sunset and flickers of light on the hills in the evening was breathtaking. Overall we had a great experience. The staff was incredibly helpful and amenities were great. The rooms were clean, very comfortable and specious with excellent service. The food was really good as well.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Great value",
    author: "Prakash J.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Excellent location.Nice food, Luxurious rooms.recmonded to all\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Surender B.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Luxurious hotel rooms and food service excellent.location is very nice.\n\n\nNearby activities: Very good activities near by.\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Vinni K.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Excellent in every field of hospitality. Spacious and clean rooms, good facilities, l9cation and most importantly efficient and quick service by a team of dedicated and cheerful staff. Food was amazing, thanks to Sunder, the chef. In all we had a wonderful experience from the first call to the owner, Mr. Hemraj till the setoff by Manager Mr. Suresh.\n\nNoteworthy details: An excellent team and dedicated service. They take care of all little points.\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Quiet, Great value",
    author: "Krishna K.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Good location.. Good food . Good hospitality.. Good staf\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Sandeep V.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Property is excellent.But some less staff in f & b . Rooms are with modern facilities.Food is good. Front desk staff is very courteous\n\nRecmonaded to all.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Mahesh K.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "I went with my family here in Feb22 and it was one of the best experiences i have ever had while holidaying in the hills. The location is amazing. It gives you a sense of remoteness with amazing views but its only 10 minutes drive from the main highway.\nThe rooms are very aesthetically done and very functional.\nGeneral service is prompt and courteous.\nBest part is the food in the restaurant. The quality and quantity is top notch. Definitely worth staying with family and friends if you plan to go through Himachal.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Abhishek B.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Good location.good food , good service by hotel Le halchal\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "K.M G.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Great location , awesome hotel, staff and food.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Geeta R.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Nice location. Good food, good rooms.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Achharjit S.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Sach a amazing hotel\nFood was good specially thankx to\nM. R Mahender singh very cooperative\nAll staff was nice well grooming\nStaff i recommended my all friends amd faimly\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Vinay G.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Praveen ji and Mahesh ji from the restraunt were very hospitable, kind, always-smiling and did their duties with utmost dedication. They had no frown on their faces if someone asked help..very generous....rest of the staff was also very helpful..thank you for the peaceful stay..highly recommended\n\nNoteworthy details: Praveen ji and Mahesh ji from the restraunt were very hospitable, kind, always-smiling and did their duties with utmost dedication. They had no frown on their faces if someone asked help..very generous....rest of the staff was also very helpful..thank you for the peaceful stay..highly recommended\n\nRooms: 5/5 | Service: 5/5 | Location: 4/5\n\nHotel highlights\nQuiet",
    author: "Bhiminder S.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Great View\n\nGood food\n\nLuxurious rooms\n\nEverythings are lajwab\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Ghanshyam K.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Good food , excellent location,\n\nBest service, good desk staff\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat value",
    author: "Ramesh L.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "One of the best hotel in Barog near by kasauli and solan . Excellent food prepared by Chef Rakesh.Most of people liked Punjabi kadi pakora .Best rooms with all modern facilities.Location is very nice. Staff and Management is perfect.G.M. is very professional and handle the all problems. Recommended to all.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Santosh S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Good location. Good food,excellent service\n\n\nRooms: Luxurious rooms\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Romantic, Child-friendly",
    author: "Hardeep S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Such a fantastic experience at the hotel! Its great to hear that you enjoyed the location, room cleanliness, and excellent service. Recommending it to your friends is a wonderful gesture!\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Aradhana P.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Very good hotel. And budgeted hotel . Luxurious all facilities like Five star.Good food ,good staff. Front desk very courteous.\n\nLocation is so nice.Recmanded to all.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Kamaldeep K.",
    date: "May 2024",
    rating: 5,
  },
  {
    text: "If you visit Solan, this is maybe the best place to stay. The rooms, ambience, rooftop, cleanliness everything was amazing. The service was bit slow but the staffs were courteous enough to ignore that fact. The quality of food was very good and 1 portion is sufficient for 2-3 people.\nRooms: 5/5 | Service: 4/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Child-friendly",
    author: "Debmalya C.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "The hotel is very nice. Well maintained spacious rooms, excellent service, helpful staff and tasty food. The only factor to consider is that the hotel is not exactly in Kasauli but its in Barog. If you search on the internet for kasauli, the name appears but be aware while booking that its not in Kasauli. So you will have to travel down to Kasauli. We had booked through Agoda and the rates were not expensive. Alternatively, you can call up the hotel and look for other offers as well. Very good experience overall\nRooms: 5/5 | Service: 5/5 | Location: 4/5",
    author: "Suwarna B.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Mr. Sharma Manager is very great person food is are excellent. We are from Nufarma and we enjoyed very much . Rooms are given five star . Recmonded to all family friends,and all unmarried couples.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Harpinder S.",
    date: "May 2024",
    rating: 5,
  },
  {
    text: "Exultant staff good location......\n\nFood was delicious\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Raj K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Amazing experience! Great Hospitality and delicious food.\n\nThe rooms are very clean and have a great valley view. The staff and the manager go out of their way to make your stay comfortable.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Great value",
    author: "Rajat D.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Stay is very pleasant, tidy and in nature's lap.\nRooms are well lit, comfortable beds. Staff is friendly.\nOverall I would say we had a Great experience with all the party and hosting.\n\nRooms: Rooms are quite comfortable and temperature controlled.\n\nNearby activities: Party hosting and live singing & traditional himachali dance performance (Nati) is great experience.\n\nWalkability: Lift service along with stairs is plus point.\n\nFood and drinks: Food/drinks are delicious and fruits and all are also great.\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Great value",
    author: "Prashant B.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Beautiful location .Barog Hills Kadauli Solan H.P. Nice food,Nice staff excellent hospitality by Mr. Sharma .G.M.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sonu A.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "Good property with excellent service n staff.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat value",
    author: "Vinay V.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "It was a wonderful stay at Hotel Le Halcyon. We were a family group of 25 people and everyone enjoyed staying at this property. Very quite, located in nature's lap, easy approach, very friendly and cooperative staff. Food was excellent. All major amenities were available. Even one of the owners took pain in getting things aligned. Quite reasonable. Little parking space.\n\nRooms: Comfortable rooms with all amenities, good space with quality products/fixtures. A separate hall is available for small get together.\n\nSafety: All corners are covered with CCTV, outside people have less access inside. Lift is available till top floor.\n\nFood and drinks: Excellent food and served with love. Whatever you ask for, they will arrange.\n\nRooms: 4/5 | Service: 5/5 | Location: 4/5\n\nHotel highlights\nGreat view, Quiet, Child-friendly",
    author: "Varun S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Overall experience was good food was good . Service was good . Faculty was cooperative. But there was little disturbance due to construction going on near the room . But otherwise it was a nice stay .\n\nSafety: It was located at safe location and nice view. There was little disturbance due to construction going on . Construction should b done in off season .\n\nFood and drinks: Food was good\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Child-friendly",
    author: "Pavneet K.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Amazing hospitality and great location. 100% recommended for a peaceful and a calm stay. Mr. Bijay Sharma went out of the way to make our stay comfortable. Great valley views from all the rooms. Well maintained spacious rooms with attention to details. Couldnt have asked for more.\nFood was also great, totally recommend for your next stay.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Tushar N.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "If you want to know whats flawless hospitality you must visit Hotel Halcyon. Each and every staff member to Mr. Sharma everyone is extremely polite and take well care of their guests.\nThe rooms are spectacular and hotel is located at a good location with ample parking space.\nFood is really tasty too.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Drishti D.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Excellent service.good food . luxurious rooms\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Narender S.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Newly constructed and well managed hotel at awesome location with a beautiful and charming views of green hills and lots of pine trees from every room and balcony. My room size was big with a bunk bed for my elder kids. All the staff members are gentle. All the food during our 3 days trip were delicious. All in all, an excellent value for money option for any traveller visiting this area.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Raj V.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Beautiful property. Rooms are clean and maintained. Location is really nice. One can enjoy both evening drinks and morning Tea/coffee with a view.\n\nMr. Vijay Sharma will attend you so nicely. He is really professional and polite at his work. He can even suggest you things to do around.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, High-tech",
    author: "Ankush S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "I had the pleasure of staying at this hotel for two nights with office colleagues. I have to say that I was very impressed with the service we received during our stay. The room was comfortable and clean and the staff was friendly and helpful. The breakfast buffet was delicious and the variety of items available was great.Overall, I had a great experience and would definitely stay at your hotel again.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Ekta P.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "We were very happy, Suresh Sharma helped us in everything. I would definetly visit again.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Priyanka T.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "Nice hotel in Kasauli barog hills . Nice food .Nice location.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Lalita V.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "The facilities and the service provided by the hotel were very nice. The staff was very humble. Food quality was good\nRooms: 5/5 | Service: 5/5 | Location: 4/5\n\nHotel highlights\nGreat view, Quiet, Child-friendly, Great value",
    author: "Shunti G.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Awesome property with professional courtesy staff and managers, and large room with all rooms have balcony view of beautiful surrounding mountains and very big comfortable bed and clean and adequate bathroom. Good breakfast restaurant offers very good cuisine at very competitive prices, hotel roof top view is amazing you can seat with family and friends and can chill the atmosphere of mountains, also have privet party place is super amazing. And enough parking space for cars, Highly recommended this property.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Mahi K.",
    date: "March 2022",
    rating: 5,
  },
  {
    text: "Today we had a lunch at LeHalcyon food was so delicious,Services was excellent We meet with Mr Mahinder and he Provide excellent information and service about the hotel .we surely plan our future group plan with them thanks for the lunch\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Nikhil B.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "It's a brand new hotel at awesome location with view of hills and pine trees from every room and balcony. Room size is really good. Staffs are extremely courteous and food was yummy to say the least. All the items during our 3 days trip were delicious. All in all, an excellent value for money option for any traveller visiting this area.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Pranay R.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Excellent service. Good food. Good location.\n\n\nRooms: Luxurious\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Gurpreet K.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Really it was amazing facilities and services provided... Thank you!\n\n\nRooms: Good services\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Roshan V.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Very neat and tidy rooms with scenic view.Staff is very friendly and hospitable. Food quality was awesome!!!!\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat value",
    author: "Harjit S.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "A nice place for family stay . All staff very nice and cordial. GM Sh. Suresh Sharma and all other staff is very friendly , cordial with nice hospitality.\n\nRooms: Rooms are spacious and well furnished.\n\nSafety: Very safe.\n\nWalkability: Just near kumarhati\n\nFood and drinks: Very nice preparation\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Prof R.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "This place is best for the people who want some relaxation form the hustle life of cities..the staff went above and beyond to make us comfortable.they were well mannered..the food was delicious.. rooms were clean and cosy .. over all Loved this place..\nRooms: 4/5 | Service: 5/5 | Location: 5/5",
    author: "Surbhi M.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Really nice and very neat and clean rooms and along with viwe food was excellent\nService and food great\nAnd good familiar hotel wonderful stay\nSpecial thanks M. R Mahender singh\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat value",
    author: "Gippy D.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Everything is excellent.\n\nCourtesy front desk staff.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Deepanshu S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Vijay Sharma, Vinay Khurana and Mahesh Thakur has given best services. Room Service, Room cleaning, room interior and food everything is awesome.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sunit M.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Nice food nice service good hospitality.\n\nAdvise to all that visit this place.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic, Great value",
    author: "Tarlok S.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "I stayed as newly married couple there around five days . So first of all if I start with my experience , then it was totally fabulous experience out there and I enjoyed my golden trip with my wife . We had very great gesture welcome by the staff with tilak and sweet on the entrance , that was really sweet gesture of them and room was decorated and room was very neat and tidy . properly managed and very clean washroom . Room service is also great point to tell , just step ahead from call . Rooms have great view to enjoy and also enjoyed snowfall out there . Staff is very cooperative . One major point to tell about here is food , really amazing and delicious food we ordered . every item by the chefs kitchen is great . that is the main reason we enjoyed our five days best . Also we had snow experience from the room , really amazing . so over all we really enjoyed our time there.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Piyush G.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Excellent is everything.\n\nLocation,food rooms\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Praduman K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Beautiful Hotel ,nice food,five star category rooms . Recommended to all families and couple. Professional Staff. G.M. Mr. Sharma is very cooperative person.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great value",
    author: "Suresh R.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "I had a very pleasant stay. The staff was really helpful and courteous.Rooms were very clean and modern. Great breakfast as well.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Quiet",
    author: "Ashish C.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Awsm experience with good hospitality with clean rooms and cooperative staff\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Gurwinder S.",
    date: "October 2024",
    rating: 5,
  },
  {
    text: "Very good hotel, appears to be newly constructed. Good service, neat and clean rooms, tasty food, worth visiting if staying at Kumarhatti.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nQuiet, Child-friendly, Great value",
    author: "Rahul K.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "It sounds like you had a wonderful experience at the hotel! Great locations, delicious food, and excellent service all contribute to a memorable stay.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Mahender S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Best view and ambience. Neat and clean rooms. Very polite and helpful staff.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Child-friendly, Great value, High-tech",
    author: "Abhishek J.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Excellent service.\nBeautiful location.\n\nRooms: Luxurious\n\nRooms: 5/5 | Service: 5/5\n\nHotel highlights\nLuxury",
    author: "Balram K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "One of the best property and best people there for hospitality. Rooms were neat and clean, views from the balcony is majestic, very very tasty breakfast buffet and in house restaurant was there. I will keep on coming to this place again and again. Special thanks to Mr. vijay sharma for very warm hospitality.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Mahesh S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Courteous staff. Great room and awesome food.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nQuiet, Great value",
    author: "Bharat B.",
    date: "October 2024",
    rating: 5,
  },
  {
    text: "Excellent property. Food is awesome.\nRooms: 5/5 | Service: 5/5 | Location: 4/5\n\nHotel highlights\nLuxury",
    author: "Dr J.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Our stay was exceptional!\n\n\nThe staff were friendly, and the room was beyond comfortable.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Megha G.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Wonderful place for staying with family. They have friendly staff and has every facility. I must say if you are planning to stay with family for vacation, just go without even second thought. Every room is with wonderful view and their food is awesome. Hospitality is beyond imagination. They are too good.",
    author: "Rahul V.",
    date: "March 2022",
    rating: 5,
  },
  {
    text: "Best location for staycation, view from the rooms are amazing. Food is fantastic will recommend this place to everyone.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Puneet N.",
    date: "June 2024",
    rating: 5,
  },
  {
    text: "It was really a great place to stay, very peaceful ambience. Rooms are really nice and clean. All facilities are 5 star. Hotel staff is very good and food is delicious and fresh . Room service is very good. Thanks for making our stay so good and memorable.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Manmeet C.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "V good Behaviour. Sharma G. M. Is very nice person good food good rooms excellent location . recommend to all\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Karan S.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Beautiful property,with fabulous view great service\n\nGood food I recommended for my all friends\n\nAnd specially thankx to M.r Mahender singh and Suresh sharma ji....\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Gurvinder S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "It Was a amazing experience to visit Hotel Le Halcyon, we planned for 2 night stay initially but after coming here and looking at the hospitality and Location we extended to 4 nights .\nBest Price, value for Money. Hygiene Rooms and washroom .\nLocation is so convenient to visit Chail and Shimla from here , we all went to nearby places very easily with 1.5 to 2 hrs travel and back to hotel .\nThey also have good Food Veg and non veg options , chef is really nice and staff is very cooperative.\n\nMust Recommended place in town For stay as wheather is awesome always hardly fan is required.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Naveen P.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Hi All, Hotel Le Halcyon is a must place to stay if you planning to visit Kasauli with friends and family.....i planned this trip with my kids and it was an excellent experience during my stay from 28th Dec 2022 till 1st Jan 2023 . The rooms were excellent , the staff is very cooperative and above all the food is delicious. It is a complete package with a sense of safety and security as well. A must visit for sure .\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Nischal M.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Nice hotel nice location viwe was amazing\n\nStaff was cooperative\n\nRooms and terrace exilant\n\nHighly recommended\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Aiosolution I.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Our stay at Le Halcyon was extremely pleasant. With great ambience, food and hospitality I must say it is Home away from Home.\n\nAnd specially thanks to Mohinder ji\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Quiet, Child-friendly, Great value",
    author: "Yogesh S.",
    date: "June 2024",
    rating: 5,
  },
  {
    text: "It was a pleasant stay.The view is very beautiful. Rooms are very neat and clean and food is amazing but you can find little bit costly. Staff was humble and polite.\nMr Suresh Sharma is very helpful in case of any help is required.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sunny B.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Great stay nice location\n\nFood and rooms are beautiful and luxury\n\nI recommend my family and friends   \nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Tek C.",
    date: "June 2024",
    rating: 5,
  },
  {
    text: "Amazing hotel and truly 5 star!\nLiked the Interiors as well as exteriors. The view from the hotel balcony is like you are either in manali or mussorie. The furniture is totally different and exquisite. Very beautiful and elegant. Looks gorgeous at each and every corner of the hotel. It is absolutely clean and beautifully maintained. Covid norms were followed at every stage. Over, all fantastic Being our happy new year celebration the management has sent a beautiful cake for the occasion. We always cherish that moment. Thanks for the Le halcyon management. We truly enjoyed our stay.",
    author: "Nipun A.",
    date: "March 2022",
    rating: 5,
  },
  {
    text: "Good hotel nice location service exilant....\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Shobit S.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Wonderful stay here\nHotel le Halcyon barog\nAmazing location food was good\nStaff was exilant\nHighly recommend\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Pundir A.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Staff , location, preparation of food n weather excellent .cant say or write more in words.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Jai K.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "Everything is fine thank you for best service\n\nRooms: Very nice\n\nFood and drinks: \n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Sandeep S.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Absolutely loved the place, its located in a hilly setup - serene, peaceful and surrounded by lush green trees. This hotel is a must recommend for your vacation to the mountains - clean and hygienic rooms, well maintained, great food and location. The hotel staff Mr. Suresh, Shashi and John (Food) are extremely courteous and supportive for your needs round the clock. Will visit again ..\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Abhishek C.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "One of the Best Place to Stay.\nRooms are well managed and cleaned.\nLocation is perfect, specialy balcony area with great view.\nFood is also good, Mr. Sharma and Mr. Tushar is so nice during our visit.\nBest Hotel in this price range..\nRooms: 5/5 | Service: 5/5 | Location: 4/5",
    author: "Mohit",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Hotel located at barog hills . excellent location.good food rooms are really five star.specially Mr Sharma G.m.is very cooperative.Recmond to all.\n\nRooms: Luxury\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great value",
    author: "Naveen S.",
    date: "April 2024",
    rating: 5,
  },
  {
    text: "The ambeince was very tranquil and calm. The place and view in itself was literally adorable and the services and staff was friendly and perfect!!\n\nNearby activities: Kasuli, Mohan Haritage National Park, Shimla, Kufri, Barog and may more.\n\nRooms: 5/5 | Service: 4/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Rajeev B.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "I visited with my family and parents to this property on 15th july 2022 for two days. No words for the experience i took here. All the hotel staff as well as Mr Suresh , Mr Shashi given a nice welcome to us . The service and food quality was 105% out of of 100. The location and weather feels you like you are walking in the clouds. The value for money hotel with extreme nature , no traffic, no crowd only nature and you. I would like to visit again and again here.\n\nHemant Verma (Delhi)",
    author: "Prince C.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Hotel Le Halcyon is a beautiful place to stay at Kasauli Hills, Baraug. It has 15 Super Deluxe and 3 Deluxe Rooms, which offer ample space, comfort and luxury of a 4 star hotel in a great package which a person dreams of to stay with family.\n\nStarting from awesome hill view to luxury of hotel which includes Spacious Rooms, Personal Balcony, Smart TV, Free Wi-Fi, Dedicated Study Desk, Chair & Tables, Almirah, Complimentary Tea /coffee maker in room, 24x7 Hot water, Ultra luxury bath fittings etc.\n\nRestaurant offers delicious food of you choice. Package gives choice of both buffet and Ala-carte food.\n\nStaff and Service is excellent. Happy to stay at hotel.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Vikas A.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Paisa vasul.\nNice location\nNice rooms\nNice food\nFive star\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sukhvir M.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "Courtesy front desk staff.\n\nGood food.luxury rooms . beautiful locations\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Aman S.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Awesome place for a soothing experience. Basic facilities like wifi, TV available. View from Hotels balcony gives a feeling of being at any renowned sun set point. Good food available and cooperative staff.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Akansha P.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Nice Stay rooms are very neat and clean.Food is awesome and service is very good.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Arvind K.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Good familiar hotel.\nFood also very testy.\n\nFood and drinks: Good\n\nNoteworthy details: Good\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Ranjit N.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Hotel location, Valley view, quiet rooms and delicious food.",
    author: "Vinayak P.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Good experience\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Quiet",
    author: "Nanda K.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "Very nice hotel hai kasauli barog hills solan. And we enjoyed it with each other.\n\nRooms: And we will also say\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Karam J.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "I enjoyed the hotel a lot, thank you hotel team.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Jalap T.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Good food, good location, good behavior of front desk staff.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Amit N.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Very good hotel in Barog kasoli hills\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Vineet K.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Best hotel in Barog kasouli.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic, Child-friendly",
    author: "Deepak V.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Good hotel in kasauli......\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Child-friendly",
    author: "Dev S.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Very good hotel bhout achi location maja agya Bhai \nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Vikas S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Maja aa gya\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Ajay R.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Good Hotel in Barog Kasauli\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Great value, High-tech",
    author: "Sheetal T.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Excellent experience.\nPaisa the vessel.\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Mahima S.",
    date: "September 2024",
    rating: 5,
  },
  {
    text: "Watering service is best\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Romantic",
    author: "Akash S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Too bad\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sanjay B.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "This place is very close to nature. This place is very beautiful, away from the crowd. The food in the hotel is very delicious.\nRooms: 4/5 | Service: 4/5 | Location: 4/5",
    author: "Chinmay K.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Best hotels in Barog himachal pradesh.\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Mohit K.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Dare \nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great value",
    author: "Trisha K.",
    date: "April 2024",
    rating: 5,
  },
  {
    text: "Very nice place\n\n\nWalkability: Padal bhut chalna padta hai\n\nRooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Sonu K.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "excellent\nRooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Saorabh K.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Child-friendly",
    author: "Shwethan P.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Harmesh S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 4/5 | Service: 4/5 | Location: 4/5\n\nHotel highlights\nGreat view",
    author: "Rahul S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Jayant S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Great value",
    author: "Kabir N.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 4/5",
    author: "Shelendra S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Anita M.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic",
    author: "Satya P.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 4/5 | Location: 5/5",
    author: "Bhavik B.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Nalinaksh B.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Nidhi S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Amit Y.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Abhiraj P.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 4/5 | Location: 5/5",
    author: "Rajeev G.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 4/5 | Location: 4/5",
    author: "Rakesh S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Good Service",
    author: "Manika T.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Little F.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Venkat S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Anmol V.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sunil G.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Anuj M.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Jaswinder M.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5",
    author: "Exotic I.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sunil P.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Shiwani S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Dinesh S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Robin A.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Raman S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Con",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Rakesh T.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 4/5",
    author: "Hitesh N.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Subhash K.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sonia S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Bipin V.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 4/5",
    author: "Abhav S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Anshika G.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "",
    author: "Hemant V.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Vijay R.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Shalu R.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Deejay R.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Rg S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 4/5 | Location: 5/5",
    author: "Lakshya G.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Amit M.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Raghav C.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Shantnu M.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Aditya K.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sahil A.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Amit S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Positive S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Padmanabhan",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 4/5 | Service: 5/5 | Location: 5/5",
    author: "Deeepak D.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Nikita A.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Raghunath P.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sunil G.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Yashwant R.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 4/5 | Service: 5/5 | Location: 5/5",
    author: "Akriti G.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 4/5 | Service: 5/5 | Location: 5/5",
    author: "Dr R.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Viveksaagar C.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Yukti",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Dr. R.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Rai S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 4/5 | Service: 4/5 | Location: 4/5",
    author: "Devansh S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "",
    author: "Monica M.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Manoj B.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Ankur T.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Rohit R.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Ashwani S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Bhuvnesh K.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Kartikey S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Gaurav A.",
    date: "March 2022",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Roshan V.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sunaina K.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Gurpreet K.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 4/5 | Service: 4/5 | Location: 4/5",
    author: "Shilpi K.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "",
    author: "Manish S.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Preeti P.",
    date: "March 2022",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Pushap R.",
    date: "March 2022",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Kuldeep D.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Kuldeep S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Chandan G.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sunil K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Yakub K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat value",
    author: "Shrenik K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Nishu T.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Dine R.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Vinay N.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Vivek",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Vikram S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Hitesh V.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5",
    author: "Sunil T.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Sangita S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Debjani S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Anant K.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "",
    author: "Vikram J.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "",
    author: "Gaggi A.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Rajan A.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Jaiswal S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Narinderpal S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "",
    author: "Divyank C.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Quiet",
    author: "Amit N.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 4/5\n\nHotel highlights\nGreat view",
    author: "Parmod S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Ravicharan S.",
    date: "February 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Joshi J.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Romantic",
    author: "Joshi J.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Mahi C.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Parveen K.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Great value",
    author: "Parveen G.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Kannu G.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Raman K.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Anil J.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view",
    author: "Jaipal S.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "B K.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Child-friendly",
    author: "Dayanand V.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Child-friendly",
    author: "Abhi K.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic, Quiet, Child-friendly",
    author: "Naresh K.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic",
    author: "Gurvinder W.",
    date: "January 2025",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Pankaj G.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nRomantic, Quiet, Child-friendly",
    author: "Rakesh K.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Bhuvan A.",
    date: "December 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 4/5 | Location: 5/5",
    author: "Nitin S.",
    date: "November 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Arun S.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Surender S.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Anmol G.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Vicky B.",
    date: "August 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Child-friendly",
    author: "Sanjukta T.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Tanishq",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Child-friendly",
    author: "Nutrition C.",
    date: "July 2024",
    rating: 5,
  },
  {
    text: "",
    author: "Vikas S.",
    date: "June 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Bittu R.",
    date: "June 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Prince A.",
    date: "May 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Srinuvas J.",
    date: "April 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Asmit S.",
    date: "April 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Arun P.",
    date: "April 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury",
    author: "Rakesh K.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Ayushi N.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view",
    author: "Rinder P.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Ananya S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Singh A.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nLuxury, Great view, Romantic, Quiet, Great value",
    author: "Gaurav B.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Minakshisingh",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 3/5 | Location: 4/5\n\nHotel highlights\nGreat view",
    author: "Pawan K.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 4/5",
    author: "Karanveer S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Kuldeep S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Prakhar S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Richie C.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Kalavathi S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat value",
    author: "Sukriti J.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5\n\nHotel highlights\nGreat view, Quiet, Child-friendly, Great value",
    author: "Anil S.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 4/5 | Location: 5/5",
    author: "Swechchha G.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Shubham T.",
    date: "March 2024",
    rating: 5,
  },
  {
    text: "",
    author: "Debashish G.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "",
    author: "Mayank P.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Manjinder K.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "",
    author: "Jeremiah D.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Lipin M.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sushant'S L.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Sunil K.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "",
    author: "Parveen K.",
    date: "March 2023",
    rating: 5,
  },
  {
    text: "Rooms: 5/5 | Service: 5/5 | Location: 5/5",
    author: "Prem K.",
    date: "March 2022",
    rating: 5,
  },
];
